name: Build Windows
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  BUILD_TYPE: Release
jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Create mixpanel_project_token.key file
        run: echo "${{ secrets.MIXPANEL_PROJECT_TOKEN }}" > Assets/mixpanel_project_token.key
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: blocks_win
          path: |
            D:/a/blocks/blocks/build/blocks_artefacts/Release/VST3/blocks.vst3/Contents/x86_64-win/blocks.vst3
            D:/a/blocks/blocks/build/blocks_artefacts/Release/LV2/blocks.lv2
            D:/a/blocks/blocks/build/blocks_artefacts/Release/Standalone/blocks.exe
  upload-to-s3:
    needs: build
    uses: ./.github/workflows/upload-to-s3.yml
    secrets: inherit
    with:
      file-name: blocks_win
