name: Build Linux
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  BUILD_TYPE: Release
jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Create mixpanel_project_token.key file
        run: echo "${{ secrets.MIXPANEL_PROJECT_TOKEN }}" > Assets/mixpanel_project_token.key
      - name: Update packages
        run: sudo apt update
      - name: Setup JUCE dependencies
        run: sudo apt install libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev mesa-common-dev
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: blocks_linux
          path: |
            ${{github.workspace}}/build/blocks_artefacts/Release/Standalone
            ${{github.workspace}}/build/blocks_artefacts/Release/VST3
            ${{github.workspace}}/build/blocks_artefacts/Release/LV2
  upload-to-s3:
    needs: build
    uses: ./.github/workflows/upload-to-s3.yml
    secrets: inherit
    with:
      file-name: blocks_linux
